name: Docker

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      matrix:
        include:
          - version:
              server: 12.19.31
            chef_flavor:
              repo_name: chef-server
              server_subdir: opscode
            base:
              image: ubuntu
              tag: 18.04
          - version:
              server: 15.10.12
              latest: true
            chef_flavor:
              repo_name: chef-server
              server_subdir: opscode
              server_user: opscode
            base:
              image: ubuntu
              tag: 24.04
          - version:
              server: 15.10.12
              latest: true
            chef_flavor:
              repo_name: cinc-server
              omnitruck: https://omnitruck.cinc.sh/install.sh
              server_project: cinc-server
              server_subdir: cinc-project
              server_user: cinc
            base:
              image: debian
              tag: 12

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.chef_flavor.repo_name }}
          tags: |
            type=raw,value=latest,enable=${{ matrix.version.latest == true }}
            type=raw,value=${{ matrix.version.server }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BASE_IMAGE=${{ matrix.base.image }}
            BASE_TAG=${{ matrix.base.tag }}
            SERVER_VERSION=${{ matrix.version.server }}
            CLIENT_VERSION=${{ matrix.version.client }}
            OMNITRUCK_URL=${{ matrix.chef_flavor.omnitruck }}
            SERVER_PROJECT=${{ matrix.chef_flavor.server_project }}
            CLIENT_PROJECT=${{ matrix.chef_flavor.client_project }}
            SERVER_SUBDIR=${{ matrix.chef_flavor.server_subdir }}
            SERVER_USER=${{ matrix.chef_flavor.server_user }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
